name: Deploy With Maven
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    if: >-
      ${{ !startsWith(github.event.head_commit.message, 'docs:')
      && !startsWith(github.event.head_commit.message, 'style:')
      && !startsWith(github.event.head_commit.message, 'ci:') }}
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven
        uses: s4u/maven-settings-action@v2.6.0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          overwrite-settings: false
      - name: Deploy with Maven
        run: mvn -B deploy --file pom.xml